spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xierenjuan/myRepository.git
          search-paths: redpackage-service
  application:
      name: config-server
server:
    port: 8802