spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xierenjuan/springcloudFinchley.git  # gif²Ö¿â
          search-paths: configdir  # ²Ö¿âÏÂµÄÄ¿Â¼
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9900/eureka
  application:
      name: config-server
server:
    port: 8802